sudo: required

services:
  - docker

before_script:
  - |
    if [ "xfalse" == "x$TRAVIS_PULL_REQUEST"]; then
      echo "Logging in to docker hub..."
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    fi

script:
  - docker build -t tanibox/build-base -f docker/build-base/bionic/Dockerfile .

after_success:
  - |
     if [ "xfalse" == "x$TRAVIS_PULL_REQUEST" ]; then
        echo "Pushing images to docker hub..."
        docker push tanibox/build-base
     fi

